baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Marvin LC Hoffman'
theme = 'ananke'

[pagination]
    disableAliases = false
    pagerSize = 2
    path = 'page'

[params]
    subtitle = 'cool author quote'
    [params.contact]
        email = 'marvin@marvinlchoffman.com'
        

sectionPagesMenu = 'main'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menus.main]]
    name = 'Works'
    pageRef = '/works'
    weight = 30
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 40
